### ISSUE TITLE
Is the 'IS' operator going to be implemented soon?

### ISSUE THREAD

**Issue by bryantaustin13** [cqframework/cql-execution#129]
I see the pull request for the 'IS' operator:
https://github.com/cqframework/cql-execution/pull/114#issue-309496269.

I am working with the opioid cds services libraries and I am getting an error from the OpioidCDS_Common library:

Error: Unimplemented Expression: Is
    at Is.UnimplementedExpression.exec (expression.js:97) 

Thanks!

**Comment by cmoesel** [comment]
Hi @bryantaustin13.  PR #114 was de-prioritized at one point and hasn't come back up yet. A few things to note:

* While #114 puts support for `is` into the execution engine library, it also requires data model implementations (a.k.a., `PatientSource`s) to add support for it.  So when this PR gets merged, the [cql-exec-fhir](https://github.com/cqframework/cql-exec-fhir) library will also need to be updated in order to take advantage of it for CQL-based FHIR.
* The approach #114 takes does not support inheritance, so the `is` operator would only return _true_ for exact matches.  E.g., `First([Observation]) is Observation` would be _true_, but `First([Observation]) is Resource` would be _false_, even though every Observation is a Resource (through the type hierarchy) so it _should_ be _true_.

This limitation in the approach is the main reason why I haven't yet merged the PR -- as I'm not sure that an implementation that sometimes returns the wrong answer is better than no implementation at all.  I'd like to code up a more robust implementation that supports inheritance, but so far other activities have superseded that.

If you write code, and this interests you, we welcome pull requests and I'd be glad to discuss some possible approaches!

**Comment by bryantaustin13** [comment]
Thanks for your answer!  I am exploring what we want to do.
    On Wednesday, April 15, 2020, 01:41:03 PM MDT, Chris Moesel <notifications@github.com> wrote:  
 
 


Hi @bryantaustin13. PR #114 was de-prioritized at one point and hasn't come back up yet. A few things to note:
   
   - While #114 puts support for is into the execution engine library, it also requires data model implementations (a.k.a., PatientSources) to add support for it. So when this PR gets merged, the cql-exec-fhir library will also need to be updated in order to take advantage of it for CQL-based FHIR.
   - The approach #114 takes does not support inheritance, so the is operator would only return true for exact matches. E.g., First([Observation]) is Observation would be true, but First([Observation]) is Resource would be false, even though every Observation is a Resource (through the type hierarchy) so it should be true.

This limitation in the approach is the main reason why I haven't yet merged the PR -- as I'm not sure that an implementation that sometimes returns the wrong answer is better than no implementation at all. I'd like to code up a more robust implementation that supports inheritance, but so far other activities have superseded that.

If you write code, and this interests you, we welcome pull requests and I'd be glad to discuss some possible approaches!

**Comment by brynrhodes** [comment]
@cmoesel , we have some logic we'd like to run that needs this operator, any pointers on how we can implement that? The minimal implementation would work for our use case, but I agree something that gives the wrong answer some of the time is worse than something that errors, so I'd like to do a correct implementation.

**Comment by cmoesel** [comment]
Hey @brynrhodes -- thanks for asking.  Here's what I'm currently thinking, but I'd love to hear any ideas you might have:

Have objects returned by the "PatientSource" (i.e., the data model provider) optionally support an `is` function that takes a type as the argument.  Then the `Is` implementation in `cql-execution` might contain something like this:
```js
if (typeof(obj.is) === 'function') {
  return object.is(this.expectedType);
}
```
This would mean that PatientSource implementations (like `cql-exec-fhir`) would need to be updated to support this.  I don't think, however, that would be very difficult, as `cql-exec-fhir` can use the modelinfo to make the determination.  We'd also need to update the classes that represent CQL datatypes (like `Quantity`, `Interval`, `DateTime`, etc) to also support `is` functions.  And we'd need some support to handle `is` for primitive JS types (e.g., if it's a JS `String` or `Number`).

Does that sound reasonable?  Do you have other ideas?  How does the Java engine do it?

**_NOTE: I am currently wrapping up a HUGE refactor that converts all the coffee source to ES6 source; so if you are thinking of implementing this, we should coordinate -- as putting big changes into the coffeescript source will only cause me headaches now!_**

**Comment by cmoesel** [comment]
Closing this, as we released support for the `Is` operator in CQL Execution 2.0.0.
