### ISSUE TITLE
Production usage and avail certification for eCQM

### ISSUE THREAD

**Issue by shardulbanker** [cqframework/cql-execution#131]
Hi,

Can we use this current cql execution engine in production env?
Considering open source apache licence compliance, can we acquire eCQM certification on this application?

Thanks.

**Comment by cmoesel** [comment]
Hi @shardulbanker.  As you noted, this project is Apache-licensed, so you can use it however you'd like (under the terms of the Apache licence).  That said, it's offered with no guarantees -- so if you're looking for something that _guarantees_ correctness and performance in a production environment (and/or commercial support), we can't offer that. But... this library is used for production tools like Bonnie and Cypress, and has been used in clinical environments for CDS pilots.  In any case, and with whatever software you choose, we recommend you do lots of testing to ensure it works as expected for your use case and environment.

As for eCQMs, this library is not enough on its own to process eCQMs.  If you're wanting to process QDM-based eCQM (like the CMS measures), you need to use this with other libraries as well (since `cql-execution` knows nothing about QDM, HQMF, or measure-based concepts like numerators and denominators).  For processing QDM-based eCQMs, you might want to check out [cqm-execution](https://github.com/projecttacoma/cqm-execution).

**Comment by cmoesel** [comment]
Closing as answered.
