### ISSUE TITLE
age.cql Example

### ISSUE THREAD

**Issue by joelmontavon** [cqframework/cql-execution#229]
When I try to create the JSON file for the age.sql example, I get the error: 

joel@ubuntu:~/Documents/clinical_quality_language/Src/java$ ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --format=JSON --input /home/joel/Documents/cql-execution/examples/node/age.cql --output /home/joel/Documents/cql-execution/examples/node
================================================================================
TRANSLATE /home/joel/Documents/cql-execution/examples/node/age.cql
Translation failed due to errors:
Error:[5:1, 5:28] Could not resolve model info provider for model Simple, version 1.0.0.
Error:[9:1, 9:15] Could not resolve context name Patient in model System.
Error:[12:5, 12:44] Could not resolve identifier Patient in the current library.

Is this user error or a bug?

**Comment by cmoesel** [comment]
Thanks for reporting this, @joelmontavon.  This is neither user error nor a bug.  It's actually just an important piece of information we forgot to document!  Thank you for pointing it out!

That example uses an example data model called the `Simple` data model.  Since that data model is not intended for real use, it is not built into the CQL-to-ELM translator.  Instead, you need to tell the translator where the model-info definition is so it can use it.  We do this using the `--model` flag and pointing to the `simple-modelinfo.xml` file found in this project's `src` folder.

If you adjust your command to be this instead, it should work:
> ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --format=JSON --input /home/joel/Documents/cql-execution/examples/node/age.cql --model /home/joel/Documents/cql-execution/src/simple-modelinfo.xml

(Note that I also left removed the `--output` argument since the default behavior is to generate output to the same folder as the input CQL resides).

**Comment by joelmontavon** [comment]
Thanks for clarifying! I am now able to create the JSON file for the example.

**Comment by cmoesel** [comment]
Thanks for confirming.  I am going to close this issue but create a new one to update the documentation to reflect the need to pass in the `--model` parameter for the example.

**Comment by csenn** [comment]
Hey @cmoesel 
The following is not working for me: 
`
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --format=JSON  --input ~/dev/cql-execution/examples/node/age.cql --model ~/dev/cql-execution/src/simple-modelinfo.xml
`
The error is:
`
TRANSLATE /home/craig/dev/cql-execution/examples/node/age.cql
Translation failed due to errors:
Error:[5:1, 5:28] Could not resolve model info provider for model Simple, version 1.0.0.
Error:[9:1, 9:15] Could not resolve context name Patient in model System.
Error:[12:5, 12:44] Could not resolve identifier Patient in the current library.
`
The same command does seem to be working for `using QUICK` instead of `using Simple version '1.0.0'` in age.cql. However, then the patient data does not resolve correctly because it's expecting a FHIR structure.

**Comment by rohituks** [comment]
@cmoesel - I can still see that bug is still in Open state and not resolved. So, whats the workaround for this problem?

**Comment by cmoesel** [comment]
Hi @rohituks -- I just tried this again and can confirm it is still broken.  Since the bug is in the CQL-to-ELM translator, I'd recommend commenting on the issue there (cqframework/clinical_quality_language#619) to see if there are plans to fix it soon.

The only workaround I'm aware of would be to create a Java script that can use the cql-to-elm translator library and invoke it via its API to load the custom model. Perhaps someone who works on the Translator might have a better idea though.

All that said, to be clear -- this is only needed if you're using a custom model (like the `Simple` model we created just for testing).  If you're using a supported model (like `fhir`), then you don't need to pass in a `--model` command at all.  It should just work.

**Comment by csenn** [comment]
@rohituks just to confirm what @cmoesel said, I ended up using the FHIR v4 model (which was essentially what I was trying to do get working in the first place). For instance something like: 
```
library MyLibrary version '1.0.0'

using FHIR version '4.0.1'

context Patient

define "My Statement": Sum({1,2,3,4,5})

define "Is Female": Patient.gender = 'female'
```
