### ISSUE TITLE
Internet Explorer bug with ucum.js

### ISSUE THREAD

**Issue by kjmahalingam** [cqframework/cql-execution#27]
When the `cql-execution` engine is used and opened in Internet Explorer, an error occurs due to ES6 syntax being used in the dependency `ucum.js`. This should be resolved so that Internet Explorer users can reliable use the `cql-execution` engine.

**Comment by cmoesel** [comment]
Since React projects don't usually run dependencies through babel, the ucum.js dependency isn't transpiled to ES5, so some of its ES6 syntax (e.g., `() =>`) causes problems in browsers like IE11.

Ideally, ucum.js should be updated to remove the ES6 syntax from its module.  In early May, I submitted a PR to the project that publishes ucum.js to NPM (https://github.com/Ventrom/ucum.js/pull/5).  Unfortunately, it hasn't received any attention -- so I don't know if we can expect a solution in the form of an updated NPM module.

There are two other potential solutions to the problem.  One is to force webpack to run _node_modules/ucum.js_ through babel with the appropriate plugin.  If you're using create-react-app, however, this means you have to _eject_, which isn't always a preferable solution.  The webpack/babel configuration to do this can also be tricky.

The other solution (and in fact the one I've used in one of my own projects), is to use Yarn's [selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature to force the ucum.js dependency to resolve to my fixed branch.  You can do this by adding the following to your `package.json`:

```json
  "resolutions": {
    "ucum": "cmoesel/ucum.js#es5-friendly"
  }
```

This should fix the IE11 issue in your web project that uses `cql-execution`.

**Comment by cmoesel** [comment]
we switched to a different UCUM library, so this issue is no longer relevant.
